In [2]:
import requests
import json

- 구분: 실시간
- 데이터명: 인천국제공항공사_입국장현황 정보 서비스

In [55]:
url = 'http://apis.data.go.kr/B551177/StatusOfArrivals/getArrivalsCongestion'
params ={'serviceKey' : 'ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==', 'numOfRows' : '10', 'pageNo' : '1', 'terno' : 'T1', 'type' : 'json' }

response = requests.get(url, params=params)

# encodingkey = ZD3OIVINNmYvDgo1FjLk8%2F82%2FbeKJKJhGNRb61laL%2BjH9rK6Ei0419SnoUBsvXd2%2Fe%2BUO%2FbLHa6Pq21D1CZpLA%3D%3D
# decodingkey = ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==

data = response.json()
formatted = json.dumps(data, indent=4, ensure_ascii=False)
print(formatted)

{
    "response": {
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL SERVICE."
        },
        "body": {
            "numOfRows": 10,
            "pageNo": 1,
            "totalCount": 37,
            "items": [
                {
                    "terno": "T1",
                    "entrygate": "D",
                    "korean": "0.0",
                    "foreigner": "0.0",
                    "scheduletime": "202507071450",
                    "estimatedtime": "202507071523",
                    "airport": "PVG",
                    "gatenumber": "128",
                    "flightid": "MU5011"
                },
                {
                    "terno": "T1",
                    "entrygate": "E",
                    "korean": "0.0",
                    "foreigner": "0.0",
                    "scheduletime": "202507071505",
                    "estimatedtime": "202507071512",
                    "airport": "DXB",
                    "gatenumber": "41",
                    "flightid": "EK324"
                },
                {
                    "terno": "T1",
                    "entrygate": "D",
                    "korean": "0.0",
                    "foreigner": "0.0",
                    "scheduletime": "202507071525",
                    "estimatedtime": "202507071525",
                    "airport": "SJW",
                    "gatenumber": "119",
                    "flightid": "7C8802"
                },
                {
                    "terno": "T1",
                    "entrygate": "E",
                    "korean": "0.0",
                    "foreigner": "64.0",
                    "scheduletime": "202507071525",
                    "estimatedtime": "202507071617",
                    "airport": "BKK",
                    "gatenumber": "48",
                    "flightid": "TG652"
                },
                {
                    "terno": "T1",
                    "entrygate": "E",
                    "korean": "0.0",
                    "foreigner": "0.0",
                    "scheduletime": "202507071530",
                    "estimatedtime": "202507071555",
                    "airport": "DFW",
                    "gatenumber": "49",
                    "flightid": "AA281"
                },
                {
                    "terno": "T1",
                    "entrygate": "D",
                    "korean": "0.0",
                    "foreigner": "2.0",
                    "scheduletime": "202507071535",
                    "estimatedtime": "202507071534",
                    "airport": "TAO",
                    "gatenumber": "123",
                    "flightid": "MU559"
                },
                {
                    "terno": "T1",
                    "entrygate": "E",
                    "korean": "0.0",
                    "foreigner": "0.0",
                    "scheduletime": "202507071535",
                    "estimatedtime": "202507071542",
                    "airport": "SIN",
                    "gatenumber": "31",
                    "flightid": "SQ600"
                },
                {
                    "terno": "T1",
                    "entrygate": "E",
                    "korean": "0.0",
                    "foreigner": "2.0",
                    "scheduletime": "202507071540",
                    "estimatedtime": "202507071515",
                    "airport": "SZX",
                    "gatenumber": "34",
                    "flightid": "ZH631"
                },
                {
                    "terno": "T1",
                    "entrygate": "E",
                    "korean": "0.0",
                    "foreigner": "80.0",
                    "scheduletime": "202507071540",
                    "estimatedtime": "202507071623",
                    "airport": "CDG",
                    "gatenumber": "46",
                    "flightid": "TW402"
                },
                {
                    "terno": "T1",
                    "entrygate": "C",
                    "korean": "0.0",
                    "foreigner": "0.0",
                    "scheduletime": "202507071545",
                    "estimatedtime": "202507071523",
                    "airport": "FUK",
                    "gatenumber": "111",
                    "flightid": "BX157"
                }
            ]
        }
    }
}

In [ ]:
import requests
 
# ▶ 포털에서 받은 Encoding된 서비스키 그대로 입력
serviceKey = "wMeQErx7JspmwkeUt7B5Q1k5W81LN4lnBP9u6B5WZjuyvSWtFdXP7B8vnd47MmndQrqfWzI0TmXLKUlIwKtRgg=="
 
# End Point (오퍼레이션 포함)
url = "https://apis.data.go.kr/B551177/StatusOfArrivals/getArrivalsCongestion"
 
params = {
    "serviceKey": serviceKey,
    "terno": "T1",           # T1=제1터미널, T2=제2터미널
    "numOfRows": 10,
    "pageNo": 1,
    "type": "json"           # json이 기본, 지원 안되면 xml
}
 
response = requests.get(url, params=params)
 
print(f"status_code: {response.status_code}")
print(f"Content-Type: {response.headers.get('Content-Type')}")
print("-" * 30)
 
text = response.text.strip()
if not text:
    print("❌ 응답이 비어 있습니다.")
elif "OpenAPI_ServiceResponse" in text:
    print("❌ 에러 응답(XML):")
    print(text)
    # 추가: 에러 코드 출력
    import re
    errcode = re.search(r"<returnReasonCode>(\d+)</returnReasonCode>", text)
    if errcode:
        print(f"→ 에러 코드: {errcode.group(1)}")
    errmsg = re.search(r"<errMsg>(.*?)</errMsg>", text)
    if errmsg:
        print(f"→ 에러 메시지: {errmsg.group(1)}")
else:
    try:
        data = response.json()
        header = data.get('response', {}).get('header', {})
        if header.get('resultCode') == '00':
            items = data['response']['body']['items']
            if not items:
                print("데이터가 없습니다.")
            else:
                for i, item in enumerate(items, 1):
                    print(f"--- 항공편 {i} ---")
                    print(f"공항: {item.get('airport', '')}")
                    print(f"입국장게이트: {item.get('entrygate', '')}")
                    print(f"편명: {item.get('flightid', '')}")
                    print(f"도착예정: {item.get('scheduletime', '')}")
                    print(f"도착실제: {item.get('estimatedtime', '')}")
                    print(f"내국인: {item.get('korean', '')}")
                    print(f"외국인: {item.get('foreigner', '')}")
                    print(f"여객기도착게이트: {item.get('gatenumber', '')}")
                    print(f"터미널: {item.get('terno', '')}")
                    print()
        else:
            print(f"❌ API 오류: {header.get('resultMsg')} ({header.get('resultCode')})")
    except Exception as e:
        print("❌ JSON 파싱 실패. 응답 원문 출력:")
        print(text)

- 구분: 실시간
- 데이터명: 인천국제공항공사_승객예고-출·입국장별

In [54]:
url = 'http://apis.data.go.kr/B551177/PassengerNoticeKR/getfPassengerNoticeIKR'
params ={'serviceKey' : 'ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==', 'selectdate' : '0', 'type' : 'json' }

response = requests.get(url, params=params)
print(response.content)

# encodingkey = ZD3OIVINNmYvDgo1FjLk8%2F82%2FbeKJKJhGNRb61laL%2BjH9rK6Ei0419SnoUBsvXd2%2Fe%2BUO%2FbLHa6Pq21D1CZpLA%3D%3D
# decodingkey = ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==

data = response.json() #json디코딩
formatted = json.dumps(data, indent=4, ensure_ascii=False)
print(formatted)

b'{"response":{"header":{"resultCode":"00","resultMsg":"NORMAL SERVICE."},"body":{"items":[{"adate":"20250707","atime":"00_01","t1sum1":"652.0","t1sum2":"0.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"652.0","t1sum5":"0.0","t1sum6":"765.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"765.0","t2sum1":"0.0","t2sum2":"0.0","t2sumset1":"0.0","t2sum3":"2.0","t2sum4":"0.0","t2sumset2":"2.0"},{"adate":"20250707","atime":"01_02","t1sum1":"463.0","t1sum2":"0.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"463.0","t1sum5":"0.0","t1sum6":"85.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"85.0","t2sum1":"0.0","t2sum2":"0.0","t2sumset1":"0.0","t2sum3":"32.0","t2sum4":"0.0","t2sumset2":"32.0"},{"adate":"20250707","atime":"02_03","t1sum1":"231.0","t1sum2":"0.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"231.0","t1sum5":"0.0","t1sum6":"35.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"35.0","t2sum1":"84.0","t2sum2":"0.0","t2sumset1":"84.0","t2sum3":"154.0","t2sum4":"0.0","t2sumset2":"154.0"},{"adate":"20250707","atime":"03_04","t1sum1":"186.0","t1sum2":"0.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"186.0","t1sum5":"0.0","t1sum6":"263.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"263.0","t2sum1":"222.0","t2sum2":"0.0","t2sumset1":"222.0","t2sum3":"146.0","t2sum4":"0.0","t2sumset2":"146.0"},{"adate":"20250707","atime":"04_05","t1sum1":"1474.0","t1sum2":"0.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"1474.0","t1sum5":"0.0","t1sum6":"1237.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"1237.0","t2sum1":"380.0","t2sum2":"0.0","t2sumset1":"380.0","t2sum3":"293.0","t2sum4":"0.0","t2sumset2":"293.0"},{"adate":"20250707","atime":"05_06","t1sum1":"1751.0","t1sum2":"286.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"2037.0","t1sum5":"0.0","t1sum6":"2252.0","t1sum7":"0.0","t1sum8":"851.0","t1sumset2":"3103.0","t2sum1":"752.0","t2sum2":"704.0","t2sumset1":"1456.0","t2sum3":"1479.0","t2sum4":"0.0","t2sumset2":"1479.0"},{"adate":"20250707","atime":"06_07","t1sum1":"388.0","t1sum2":"1329.0","t1sum3":"1232.0","t1sum4":"454.0","t1sumset1":"3403.0","t1sum5":"1118.0","t1sum6":"1570.0","t1sum7":"635.0","t1sum8":"950.0","t1sumset2":"4273.0","t2sum1":"213.0","t2sum2":"836.0","t2sumset1":"1049.0","t2sum3":"1660.0","t2sum4":"1112.0","t2sumset2":"2772.0"},{"adate":"20250707","atime":"07_08","t1sum1":"705.0","t1sum2":"1350.0","t1sum3":"1256.0","t1sum4":"768.0","t1sumset1":"4079.0","t1sum5":"2077.0","t1sum6":"1287.0","t1sum7":"1386.0","t1sum8":"1287.0","t1sumset2":"6037.0","t2sum1":"333.0","t2sum2":"543.0","t2sumset1":"876.0","t2sum3":"2028.0","t2sum4":"1100.0","t2sumset2":"3128.0"},{"adate":"20250707","atime":"08_09","t1sum1":"371.0","t1sum2":"586.0","t1sum3":"658.0","t1sum4":"987.0","t1sumset1":"2602.0","t1sum5":"1499.0","t1sum6":"1475.0","t1sum7":"1192.0","t1sum8":"1627.0","t1sumset2":"5793.0","t2sum1":"298.0","t2sum2":"452.0","t2sumset1":"750.0","t2sum3":"1962.0","t2sum4":"1095.0","t2sumset2":"3057.0"},{"adate":"20250707","atime":"09_10","t1sum1":"272.0","t1sum2":"506.0","t1sum3":"545.0","t1sum4":"110.0","t1sumset1":"1433.0","t1sum5":"1120.0","t1sum6":"1134.0","t1sum7":"1241.0","t1sum8":"1301.0","t1sumset2":"4796.0","t2sum1":"463.0","t2sum2":"261.0","t2sumset1":"724.0","t2sum3":"1024.0","t2sum4":"670.0","t2sumset2":"1694.0"},{"adate":"20250707","atime":"10_11","t1sum1":"0.0","t1sum2":"1132.0","t1sum3":"804.0","t1sum4":"578.0","t1sumset1":"2514.0","t1sum5":"1224.0","t1sum6":"894.0","t1sum7":"1197.0","t1sum8":"1155.0","t1sumset2":"4470.0","t2sum1":"77.0","t2sum2":"258.0","t2sumset1":"335.0","t2sum3":"942.0","t2sum4":"630.0","t2sumset2":"1572.0"},{"adate":"20250707","atime":"11_12","t1sum1":"191.0","t1sum2":"1557.0","t1sum3":"306.0","t1sum4":"677.0","t1sumset1":"2731.0","t1sum5":"995.0","t1sum6":"744.0","t1sum7":"950.0","t1sum8":"1196.0","t1sumset2":"3885.0","t2sum1":"300.0","t2sum2":"759.0","t2sumset1":"1059.0","t2sum3":"1125.0","t2sum4":"562.0","t2sumset2":"1687.0"},{"adate":"20250707","atime":"12_13","t1sum1":"477.0","t1sum2":"658.0","t1sum3":"1120.0","t1sum4":"1035.0","t1sumset1":"3290.0","t1sum5":"963.0","t1sum6":"589.0","t1sum7":"926.0","t1sum8":"1286.0","t1sumset2":"3764.0","t2sum1":"583.0","t2sum2":"374.0","t2sumset1":"957.0","t2sum3":"892.0","t2sum4":"511.0","t2sumset2":"1403.0"},{"adate":"20250707","atime":"13_14","t1sum1":"762.0","t1sum2":"1306.0","t1sum3":"463.0","t1sum4":"751.0","t1sumset1":"3282.0","t1sum5":"841.0","t1sum6":"662.0","t1sum7":"1008.0","t1sum8":"1274.0","t1sumset2":"3785.0","t2sum1":"429.0","t2sum2":"605.0","t2sumset1":"1034.0","t2sum3":"884.0","t2sum4":"523.0","t2sumset2":"1407.0"},{"adate":"20250707","atime":"14_15","t1sum1":"1020.0","t1sum2":"1254.0","t1sum3":"706.0","t1sum4":"990.0","t1sumset1":"3970.0","t1sum5":"729.0","t1sum6":"591.0","t1sum7":"845.0","t1sum8":"893.0","t1sumset2":"3058.0","t2sum1":"815.0","t2sum2":"1010.0","t2sumset1":"1825.0","t2sum3":"909.0","t2sum4":"514.0","t2sumset2":"1423.0"},{"adate":"20250707","atime":"15_16","t1sum1":"918.0","t1sum2":"1396.0","t1sum3":"1030.0","t1sum4":"870.0","t1sumset1":"4214.0","t1sum5":"642.0","t1sum6":"620.0","t1sum7":"642.0","t1sum8":"874.0","t1sumset2":"2778.0","t2sum1":"529.0","t2sum2":"926.0","t2sumset1":"1455.0","t2sum3":"751.0","t2sum4":"561.0","t2sumset2":"1312.0"},{"adate":"20250707","atime":"16_17","t1sum1":"1026.0","t1sum2":"1466.0","t1sum3":"474.0","t1sum4":"841.0","t1sumset1":"3807.0","t1sum5":"832.0","t1sum6":"658.0","t1sum7":"581.0","t1sum8":"643.0","t1sumset2":"2714.0","t2sum1":"762.0","t2sum2":"1964.0","t2sumset1":"2726.0","t2sum3":"1208.0","t2sum4":"862.0","t2sumset2":"2070.0"},{"adate":"20250707","atime":"17_18","t1sum1":"762.0","t1sum2":"1387.0","t1sum3":"841.0","t1sum4":"259.0","t1sumset1":"3249.0","t1sum5":"1138.0","t1sum6":"734.0","t1sum7":"684.0","t1sum8":"751.0","t1sumset2":"3307.0","t2sum1":"1170.0","t2sum2":"972.0","t2sumset1":"2142.0","t2sum3":"1357.0","t2sum4":"963.0","t2sumset2":"2320.0"},{"adate":"20250707","atime":"18_19","t1sum1":"926.0","t1sum2":"1722.0","t1sum3":"598.0","t1sum4":"839.0","t1sumset1":"4085.0","t1sum5":"1153.0","t1sum6":"798.0","t1sum7":"891.0","t1sum8":"986.0","t1sumset2":"3828.0","t2sum1":"636.0","t2sum2":"590.0","t2sumset1":"1226.0","t2sum3":"1069.0","t2sum4":"782.0","t2sumset2":"1851.0"},{"adate":"20250707","atime":"19_20","t1sum1":"479.0","t1sum2":"1639.0","t1sum3":"771.0","t1sum4":"1109.0","t1sumset1":"3998.0","t1sum5":"824.0","t1sum6":"629.0","t1sum7":"873.0","t1sum8":"904.0","t1sumset2":"3230.0","t2sum1":"295.0","t2sum2":"248.0","t2sumset1":"543.0","t2sum3":"1040.0","t2sum4":"0.0","t2sumset2":"1040.0"},{"adate":"20250707","atime":"20_21","t1sum1":"484.0","t1sum2":"827.0","t1sum3":"852.0","t1sum4":"664.0","t1sumset1":"2827.0","t1sum5":"0.0","t1sum6":"1681.0","t1sum7":"0.0","t1sum8":"637.0","t1sumset2":"2318.0","t2sum1":"501.0","t2sum2":"0.0","t2sumset1":"501.0","t2sum3":"436.0","t2sum4":"0.0","t2sumset2":"436.0"},{"adate":"20250707","atime":"21_22","t1sum1":"871.0","t1sum2":"683.0","t1sum3":"621.0","t1sum4":"1701.0","t1sumset1":"3876.0","t1sum5":"0.0","t1sum6":"698.0","t1sum7":"0.0","t1sum8":"341.0","t1sumset2":"1039.0","t2sum1":"1598.0","t2sum2":"0.0","t2sumset1":"1598.0","t2sum3":"257.0","t2sum4":"0.0","t2sumset2":"257.0"},{"adate":"20250707","atime":"22_23","t1sum1":"2372.0","t1sum2":"856.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"3228.0","t1sum5":"0.0","t1sum6":"593.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"593.0","t2sum1":"1005.0","t2sum2":"0.0","t2sumset1":"1005.0","t2sum3":"79.0","t2sum4":"0.0","t2sumset2":"79.0"},{"adate":"20250707","atime":"23_00","t1sum1":"844.0","t1sum2":"0.0","t1sum3":"0.0","t1sum4":"0.0","t1sumset1":"844.0","t1sum5":"0.0","t1sum6":"940.0","t1sum7":"0.0","t1sum8":"0.0","t1sumset2":"940.0","t2sum1":"390.0","t2sum2":"0.0","t2sumset1":"390.0","t2sum3":"0.0","t2sum4":"0.0","t2sumset2":"0.0"},{"adate":"\xed\x95\xa9\xea\xb3\x84","atime":"\xed\x95\xa9\xea\xb3\x84","t1sum1":"17625.0","t1sum2":"19940.0","t1sum3":"12277.0","t1sum4":"12633.0","t1sumset1":"62475.0","t1sum5":"15155.0","t1sum6":"20934.0","t1sum7":"13051.0","t1sum8":"16956.0","t1sumset2":"66096.0","t2sum1":"11835.0","t2sum2":"10502.0","t2sumset1":"22337.0","t2sum3":"19729.0","t2sum4":"9885.0","t2sumset2":"29614.0"}]}}}'
{
    "response": {
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL SERVICE."
        },
        "body": {
            "items": [
                {
                    "adate": "20250707",
                    "atime": "00_01",
                    "t1sum1": "652.0",
                    "t1sum2": "0.0",
                    "t1sum3": "0.0",
                    "t1sum4": "0.0",
                    "t1sumset1": "652.0",
                    "t1sum5": "0.0",
                    "t1sum6": "765.0",
                    "t1sum7": "0.0",
                    "t1sum8": "0.0",
                    "t1sumset2": "765.0",
                    "t2sum1": "0.0",
                    "t2sum2": "0.0",
                    "t2sumset1": "0.0",
                    "t2sum3": "2.0",
                    "t2sum4": "0.0",
                    "t2sumset2": "2.0"
                },
                {
                    "adate": "20250707",
                    "atime": "01_02",
                    "t1sum1": "463.0",
                    "t1sum2": "0.0",
                    "t1sum3": "0.0",
                    "t1sum4": "0.0",
                    "t1sumset1": "463.0",
                    "t1sum5": "0.0",
                    "t1sum6": "85.0",
                    "t1sum7": "0.0",
                    "t1sum8": "0.0",
                    "t1sumset2": "85.0",
                    "t2sum1": "0.0",
                    "t2sum2": "0.0",
                    "t2sumset1": "0.0",
                    "t2sum3": "32.0",
                    "t2sum4": "0.0",
                    "t2sumset2": "32.0"
                },
                {
                    "adate": "20250707",
                    "atime": "02_03",
                    "t1sum1": "231.0",
                    "t1sum2": "0.0",
                    "t1sum3": "0.0",
                    "t1sum4": "0.0",
                    "t1sumset1": "231.0",
                    "t1sum5": "0.0",
                    "t1sum6": "35.0",
                    "t1sum7": "0.0",
                    "t1sum8": "0.0",
                    "t1sumset2": "35.0",
                    "t2sum1": "84.0",
                    "t2sum2": "0.0",
                    "t2sumset1": "84.0",
                    "t2sum3": "154.0",
                    "t2sum4": "0.0",
                    "t2sumset2": "154.0"
                },
                {
                    "adate": "20250707",
                    "atime": "03_04",
                    "t1sum1": "186.0",
                    "t1sum2": "0.0",
                    "t1sum3": "0.0",
                    "t1sum4": "0.0",
                    "t1sumset1": "186.0",
                    "t1sum5": "0.0",
                    "t1sum6": "263.0",
                    "t1sum7": "0.0",
                    "t1sum8": "0.0",
                    "t1sumset2": "263.0",
                    "t2sum1": "222.0",
                    "t2sum2": "0.0",
                    "t2sumset1": "222.0",
                    "t2sum3": "146.0",
                    "t2sum4": "0.0",
                    "t2sumset2": "146.0"
                },
                {
                    "adate": "20250707",
                    "atime": "04_05",
                    "t1sum1": "1474.0",
                    "t1sum2": "0.0",
                    "t1sum3": "0.0",
                    "t1sum4": "0.0",
                    "t1sumset1": "1474.0",
                    "t1sum5": "0.0",
                    "t1sum6": "1237.0",
                    "t1sum7": "0.0",
                    "t1sum8": "0.0",
                    "t1sumset2": "1237.0",
                    "t2sum1": "380.0",
                    "t2sum2": "0.0",
                    "t2sumset1": "380.0",
                    "t2sum3": "293.0",
                    "t2sum4": "0.0",
                    "t2sumset2": "293.0"
                },
                {
                    "adate": "20250707",
                    "atime": "05_06",
                    "t1sum1": "1751.0",
                    "t1sum2": "286.0",
                    "t1sum3": "0.0",
                    "t1sum4": "0.0",
                    "t1sumset1": "2037.0",
                    "t1sum5": "0.0",
                    "t1sum6": "2252.0",
                    "t1sum7": "0.0",
                    "t1sum8": "851.0",
                    "t1sumset2": "3103.0",
                    "t2sum1": "752.0",
                    "t2sum2": "704.0",
                    "t2sumset1": "1456.0",
                    "t2sum3": "1479.0",
                    "t2sum4": "0.0",
                    "t2sumset2": "1479.0"
                },
                {
                    "adate": "20250707",
                    "atime": "06_07",
                    "t1sum1": "388.0",
                    "t1sum2": "1329.0",
                    "t1sum3": "1232.0",
                    "t1sum4": "454.0",
                    "t1sumset1": "3403.0",
                    "t1sum5": "1118.0",
                    "t1sum6": "1570.0",
                    "t1sum7": "635.0",
                    "t1sum8": "950.0",
                    "t1sumset2": "4273.0",
                    "t2sum1": "213.0",
                    "t2sum2": "836.0",
                    "t2sumset1": "1049.0",
                    "t2sum3": "1660.0",
                    "t2sum4": "1112.0",
                    "t2sumset2": "2772.0"
                },
                {
                    "adate": "20250707",
                    "atime": "07_08",
                    "t1sum1": "705.0",
                    "t1sum2": "1350.0",
                    "t1sum3": "1256.0",
                    "t1sum4": "768.0",
                    "t1sumset1": "4079.0",
                    "t1sum5": "2077.0",
                    "t1sum6": "1287.0",
                    "t1sum7": "1386.0",
                    "t1sum8": "1287.0",
                    "t1sumset2": "6037.0",
                    "t2sum1": "333.0",
                    "t2sum2": "543.0",
                    "t2sumset1": "876.0",
                    "t2sum3": "2028.0",
                    "t2sum4": "1100.0",
                    "t2sumset2": "3128.0"
                },
                {
                    "adate": "20250707",
                    "atime": "08_09",
                    "t1sum1": "371.0",
                    "t1sum2": "586.0",
                    "t1sum3": "658.0",
                    "t1sum4": "987.0",
                    "t1sumset1": "2602.0",
                    "t1sum5": "1499.0",
                    "t1sum6": "1475.0",
                    "t1sum7": "1192.0",
                    "t1sum8": "1627.0",
                    "t1sumset2": "5793.0",
                    "t2sum1": "298.0",
                    "t2sum2": "452.0",
                    "t2sumset1": "750.0",
                    "t2sum3": "1962.0",
                    "t2sum4": "1095.0",
                    "t2sumset2": "3057.0"
                },
                {
                    "adate": "20250707",
                    "atime": "09_10",
                    "t1sum1": "272.0",
                    "t1sum2": "506.0",
                    "t1sum3": "545.0",
                    "t1sum4": "110.0",
                    "t1sumset1": "1433.0",
                    "t1sum5": "1120.0",
                    "t1sum6": "1134.0",
                    "t1sum7": "1241.0",
                    "t1sum8": "1301.0",
                    "t1sumset2": "4796.0",
                    "t2sum1": "463.0",
                    "t2sum2": "261.0",
                    "t2sumset1": "724.0",
                    "t2sum3": "1024.0",
                    "t2sum4": "670.0",
                    "t2sumset2": "1694.0"
                },
                {
                    "adate": "20250707",
                    "atime": "10_11",
                    "t1sum1": "0.0",
                    "t1sum2": "1132.0",
                    "t1sum3": "804.0",
                    "t1sum4": "578.0",
                    "t1sumset1": "2514.0",
                    "t1sum5": "1224.0",
                    "t1sum6": "894.0",
                    "t1sum7": "1197.0",
                    "t1sum8": "1155.0",
                    "t1sumset2": "4470.0",
                    "t2sum1": "77.0",
                    "t2sum2": "258.0",
                    "t2sumset1": "335.0",
                    "t2sum3": "942.0",
                    "t2sum4": "630.0",
                    "t2sumset2": "1572.0"
                },
                {
                    "adate": "20250707",
                    "atime": "11_12",
                    "t1sum1": "191.0",
                    "t1sum2": "1557.0",
                    "t1sum3": "306.0",
                    "t1sum4": "677.0",
                    "t1sumset1": "2731.0",
                    "t1sum5": "995.0",
                    "t1sum6": "744.0",
                    "t1sum7": "950.0",
                    "t1sum8": "1196.0",
                    "t1sumset2": "3885.0",
                    "t2sum1": "300.0",
                    "t2sum2": "759.0",
                    "t2sumset1": "1059.0",
                    "t2sum3": "1125.0",
                    "t2sum4": "562.0",
                    "t2sumset2": "1687.0"
                },
                {
                    "adate": "20250707",
                    "atime": "12_13",
                    "t1sum1": "477.0",
                    "t1sum2": "658.0",
                    "t1sum3": "1120.0",
                    "t1sum4": "1035.0",
                    "t1sumset1": "3290.0",
                    "t1sum5": "963.0",
                    "t1sum6": "589.0",
                    "t1sum7": "926.0",
                    "t1sum8": "1286.0",
                    "t1sumset2": "3764.0",
                    "t2sum1": "583.0",
                    "t2sum2": "374.0",
                    "t2sumset1": "957.0",
                    "t2sum3": "892.0",
                    "t2sum4": "511.0",
                    "t2sumset2": "1403.0"
                },
                {
                    "adate": "20250707",
                    "atime": "13_14",
                    "t1sum1": "762.0",
                    "t1sum2": "1306.0",
                    "t1sum3": "463.0",
                    "t1sum4": "751.0",
                    "t1sumset1": "3282.0",
                    "t1sum5": "841.0",
                    "t1sum6": "662.0",
                    "t1sum7": "1008.0",
                    "t1sum8": "1274.0",
                    "t1sumset2": "3785.0",
                    "t2sum1": "429.0",
                    "t2sum2": "605.0",
                    "t2sumset1": "1034.0",
                    "t2sum3": "884.0",
                    "t2sum4": "523.0",
                    "t2sumset2": "1407.0"
                },
                {
                    "adate": "20250707",
                    "atime": "14_15",
                    "t1sum1": "1020.0",
                    "t1sum2": "1254.0",
                    "t1sum3": "706.0",
                    "t1sum4": "990.0",
                    "t1sumset1": "3970.0",
                    "t1sum5": "729.0",
                    "t1sum6": "591.0",
                    "t1sum7": "845.0",
                    "t1sum8": "893.0",
                    "t1sumset2": "3058.0",
                    "t2sum1": "815.0",
                    "t2sum2": "1010.0",
                    "t2sumset1": "1825.0",
                    "t2sum3": "909.0",
                    "t2sum4": "514.0",
                    "t2sumset2": "1423.0"
                },
                {
                    "adate": "20250707",
                    "atime": "15_16",
                    "t1sum1": "918.0",
                    "t1sum2": "1396.0",
                    "t1sum3": "1030.0",
                    "t1sum4": "870.0",
                    "t1sumset1": "4214.0",
                    "t1sum5": "642.0",
                    "t1sum6": "620.0",
                    "t1sum7": "642.0",

- 구분: 실시간
- 인천국제공항공사_여객편 운항현황(다국어)
    - 항공사 코드 확인을 위한 테스트 목적

In [3]:
url = 'http://apis.data.go.kr/B551177/StatusOfPassengerFlightsOdp/getPassengerArrivalsOdp'
params ={'serviceKey' : 'ZD3OIVINNmYvDgo1FjLk8%2F82%2FbeKJKJhGNRb61laL%2BjH9rK6Ei0419SnoUBsvXd2%2Fe%2BUO%2FbLHa6Pq21D1CZpLA%3D%3D', 'from_time' : '0000', 'to_time' : '2400', 'airport' : 'KAL', 'flight_id' : 'KE5040', 'airline' : 'KE', 'lang' : 'K', 'type' : 'json' }

response = requests.get(url, params=params)
print(data)

# encodingkey = ZD3OIVINNmYvDgo1FjLk8%2F82%2FbeKJKJhGNRb61laL%2BjH9rK6Ei0419SnoUBsvXd2%2Fe%2BUO%2FbLHa6Pq21D1CZpLA%3D%3D
# decodingkey = ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==

{'response': {'header': {'resultCode': '00', 'resultMsg': 'NORMAL SERVICE.'}, 'body': {'numOfRows': 10, 'pageNo': 1, 'totalCount': 1061, 'items': [{'airline': '델타항공', 'flightId': 'DL9896', 'scheduleDateTime': '0005', 'estimatedDateTime': '2356', 'airport': '시애틀', 'gatenumber': '254', 'chkinrange': 'K31-K34', 'exitnumber': None, 'remark': '출발', 'airportCode': 'SEA', 'yoil': '목', 'himidity': '67', 'wind': '3.6', 'temp': '15.0', 'senstemp': '14.3', 'wimage': 'https://odp.airport.kr/apiPortal/weather_icon/icon04', 'terminalid': 'P03'}, {'airline': '산동항공', 'flightId': 'SC8004Y', 'scheduleDateTime': '0005', 'estimatedDateTime': '2353', 'airport': '지난', 'gatenumber': '14', 'chkinrange': 'N03-N15', 'exitnumber': None, 'remark': '출발', 'airportCode': 'TNA', 'yoil': '목', 'himidity': '70', 'wind': '2.6', 'temp': '29.0', 'senstemp': '32.7', 'wimage': 'https://odp.airport.kr/apiPortal/weather_icon/icon01', 'terminalid': 'P01'}, {'airline': '중국국제항공', 'flightId': 'CA8876Y', 'scheduleDateTime': '0005', 'estimatedDateTime': '2353', 'airport': '지난', 'gatenumber': '14', 'chkinrange': 'N03-N15', 'exitnumber': None, 'remark': '출발', 'airportCode': 'TNA', 'yoil': '목', 'himidity': '70', 'wind': '2.6', 'temp': '29.0', 'senstemp': '32.7', 'wimage': 'https://odp.airport.kr/apiPortal/weather_icon/icon01', 'terminalid': 'P01'}, {'airline': '아시아나항공', 'flightId': 'OZ6705Y', 'scheduleDateTime': '0005', 'estimatedDateTime': '2353', 'airport': '지난', 'gatenumber': '14', 'chkinrange': 'N03-N15', 'exitnumber': None, 'remark': '출발', 'airportCode': 'TNA', 'yoil': '목', 'himidity': '70', 'wind': '2.6', 'temp': '29.0', 'senstemp': '32.7', 'wimage': 'https://odp.airport.kr/apiPortal/weather_icon/icon01', 'terminalid': 'P01'}, {'airline': '중국해남항공', 'flightId': 'HU450', 'scheduleDateTime': '0005', 'estimatedDateTime': '0002', 'airport': '하이커우', 'gatenumber': '20', 'chkinrange': 'E01-E04', 'exitnumber': None, 'remark': '출발', 'airportCode': 'HAK', 'yoil': None, 'himidity': None, 'wind': None, 'temp': None, 'senstemp': None, 'wimage': None, 'terminalid': 'P01'}, {'airline': '몽골항공', 'flightId': 'OM308', 'scheduleDateTime': '0005', 'estimatedDateTime': '0016', 'airport': '신 울란바토르', 'gatenumber': '21', 'chkinrange': 'K25-K34', 'exitnumber': None, 'remark': '출발', 'airportCode': 'UBN', 'yoil': None, 'himidity': None, 'wind': None, 'temp': None, 'senstemp': None, 'wimage': None, 'terminalid': 'P01'}, {'airline': '대한항공', 'flightId': 'KE5649', 'scheduleDateTime': '0005', 'estimatedDateTime': '0016', 'airport': '신 울란바토르', 'gatenumber': '21', 'chkinrange': 'K25-K34', 'exitnumber': None, 'remark': '출발', 'airportCode': 'UBN', 'yoil': None, 'himidity': None, 'wind': None, 'temp': None, 'senstemp': None, 'wimage': None, 'terminalid': 'P01'}, {'airline': '말레이시아 항공', 'flightId': 'MH039', 'scheduleDateTime': '0010', 'estimatedDateTime': '0002', 'airport': '쿠알라룸푸르', 'gatenumber': '38', 'chkinrange': 'M12-M16', 'exitnumber': None, 'remark': '출발', 'airportCode': 'KUL', 'yoil': '목', 'himidity': '79', 'wind': '0.0', 'temp': '27.0', 'senstemp': '29.6', 'wimage': 'https://odp.airport.kr/apiPortal/weather_icon/icon02', 'terminalid': 'P01'}, {'airline': '타이거에어 타이완', 'flightId': 'IT603', 'scheduleDateTime': '0030', 'estimatedDateTime': '0030', 'airport': '타이베이', 'gatenumber': '114', 'chkinrange': 'H01-H05', 'exitnumber': None, 'remark': '출발', 'airportCode': 'TPE', 'yoil': '목', 'himidity': '89', 'wind': '2.6', 'temp': '26.0', 'senstemp': '28.0', 'wimage': 'https://odp.airport.kr/apiPortal/weather_icon/icon02', 'terminalid': 'P02'}, {'airline': '에티오피아항공', 'flightId': 'ET673', 'scheduleDateTime': '0035', 'estimatedDateTime': '0030', 'airport': '아디스아바바/볼레', 'gatenumber': '23', 'chkinrange': 'F08-F17', 'exitnumber': None, 'remark': '출발', 'airportCode': 'ADD', 'yoil': None, 'himidity': None, 'wind': None, 'temp': None, 'senstemp': None, 'wimage': None, 'terminalid': 'P01'}]}}}

- 구분: 실시간
- 데이터명: 인천국제공항공사_기상 정보 (중 인천공항 출발 항공편 도착지 기상 정보)

In [ ]:
# decodingkey = ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==

url = 'http://apis.data.go.kr/B551177/StatusOfPassengerWorldWeatherInfo/getPassengerDeparturesWorldWeather'
params ={'serviceKey' : 'ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==', 'numOfRows' : '10', 'pageNo' : '1', 'from_time' : '0000', 'to_time' : '2400', 'flight_id' : '', 'airline' : '', 'lang' : 'K', 'type' : 'json' }

response = requests.get(url, params=params)
print(response.content)


data = response.json() #json디코딩
formatted = json.dumps(data, indent=4, ensure_ascii=False)
print(formatted)

b'{"response":{"header":{"resultCode":"00","resultMsg":"NORMAL SERVICE."},"body":{"numOfRows":10,"pageNo":1,"totalCount":1094,"items":[{"airline":"\xeb\xaa\xbd\xea\xb3\xa8\xed\x95\xad\xea\xb3\xb5","flightId":"OM308","scheduleDateTime":"0005","estimatedDateTime":"2358","airport":"\xec\x8b\xa0 \xec\x9a\xb8\xeb\x9e\x80\xeb\xb0\x94\xed\x86\xa0\xeb\xa5\xb4","gatenumber":"10","chkinrange":"K25-K34","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"UBN","yoil":null,"himidity":null,"wind":null,"temp":null,"senstemp":null,"wimage":null,"terminalid":"P01"},{"airline":"\xeb\x8c\x80\xed\x95\x9c\xed\x95\xad\xea\xb3\xb5","flightId":"KE5649","scheduleDateTime":"0005","estimatedDateTime":"2358","airport":"\xec\x8b\xa0 \xec\x9a\xb8\xeb\x9e\x80\xeb\xb0\x94\xed\x86\xa0\xeb\xa5\xb4","gatenumber":"10","chkinrange":"K25-K34","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"UBN","yoil":null,"himidity":null,"wind":null,"temp":null,"senstemp":null,"wimage":null,"terminalid":"P01"},{"airline":"\xec\x82\xb0\xeb\x8f\x99\xed\x95\xad\xea\xb3\xb5","flightId":"SC8004Y","scheduleDateTime":"0005","estimatedDateTime":"2352","airport":"\xec\xa7\x80\xeb\x82\x9c","gatenumber":"14","chkinrange":"N03-N15","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"TNA","yoil":"\xeb\xaa\xa9","himidity":"74","wind":"2.6","temp":"28.0","senstemp":"31.3","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon01","terminalid":"P01"},{"airline":"\xec\xa4\x91\xea\xb5\xad\xea\xb5\xad\xec\xa0\x9c\xed\x95\xad\xea\xb3\xb5","flightId":"CA8876Y","scheduleDateTime":"0005","estimatedDateTime":"2352","airport":"\xec\xa7\x80\xeb\x82\x9c","gatenumber":"14","chkinrange":"N03-N15","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"TNA","yoil":"\xeb\xaa\xa9","himidity":"74","wind":"2.6","temp":"28.0","senstemp":"31.3","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon01","terminalid":"P01"},{"airline":"\xec\x95\x84\xec\x8b\x9c\xec\x95\x84\xeb\x82\x98\xed\x95\xad\xea\xb3\xb5","flightId":"OZ6705Y","scheduleDateTime":"0005","estimatedDateTime":"2352","airport":"\xec\xa7\x80\xeb\x82\x9c","gatenumber":"14","chkinrange":"N03-N15","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"TNA","yoil":"\xeb\xaa\xa9","himidity":"74","wind":"2.6","temp":"28.0","senstemp":"31.3","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon01","terminalid":"P01"},{"airline":"\xeb\x8c\x80\xed\x95\x9c\xed\x95\xad\xea\xb3\xb5","flightId":"KE647Y","scheduleDateTime":"0005","estimatedDateTime":"2335","airport":"\xec\x8b\xb1\xea\xb0\x80\xed\x8f\xac\xeb\xa5\xb4","gatenumber":"233","chkinrange":"A B C D F","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"SIN","yoil":"\xeb\xaa\xa9","himidity":"70","wind":"2.6","temp":"29.0","senstemp":"32.7","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon02","terminalid":"P03"},{"airline":"\xeb\x8d\xb8\xed\x83\x80\xed\x95\xad\xea\xb3\xb5","flightId":"DL7823Y","scheduleDateTime":"0005","estimatedDateTime":"2335","airport":"\xec\x8b\xb1\xea\xb0\x80\xed\x8f\xac\xeb\xa5\xb4","gatenumber":"233","chkinrange":"A B C D F","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"SIN","yoil":"\xeb\xaa\xa9","himidity":"70","wind":"2.6","temp":"29.0","senstemp":"32.7","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon02","terminalid":"P03"},{"airline":"\xec\x9b\xa8\xec\x8a\xa4\xed\x8a\xb8\xec\xa0\xaf","flightId":"WS6065Y","scheduleDateTime":"0005","estimatedDateTime":"2335","airport":"\xec\x8b\xb1\xea\xb0\x80\xed\x8f\xac\xeb\xa5\xb4","gatenumber":"233","chkinrange":"A B C D F","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"SIN","yoil":"\xeb\xaa\xa9","himidity":"70","wind":"2.6","temp":"29.0","senstemp":"32.7","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon02","terminalid":"P03"},{"airline":"\xec\x8a\xa4\xeb\xa6\xac\xeb\x9e\x91\xec\xb9\xb4\xed\x95\xad\xea\xb3\xb5","flightId":"UL3815Y","scheduleDateTime":"0005","estimatedDateTime":"2335","airport":"\xec\x8b\xb1\xea\xb0\x80\xed\x8f\xac\xeb\xa5\xb4","gatenumber":"233","chkinrange":"A B C D F","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"SIN","yoil":"\xeb\xaa\xa9","himidity":"70","wind":"2.6","temp":"29.0","senstemp":"32.7","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon02","terminalid":"P03"},{"airline":"\xec\x97\x90\xeb\xaf\xb8\xeb\xa0\x88\xec\x9d\xb4\xed\x8a\xb8\xed\x95\xad\xea\xb3\xb5","flightId":"EK323Y","scheduleDateTime":"0005","estimatedDateTime":"2346","airport":"\xeb\x91\x90\xeb\xb0\x94\xec\x9d\xb4","gatenumber":"43","chkinrange":"K01-K12","exitnumber":null,"remark":"\xec\xb6\x9c\xeb\xb0\x9c","airportCode":"DXB","yoil":"\xeb\xaa\xa9","himidity":"29","wind":"4.1","temp":"37.0","senstemp":"37.4","wimage":"https://odp.airport.kr/apiPortal/weather_icon/icon01","terminalid":"P01"}]}}}'
{
    "response": {
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL SERVICE."
        },
        "body": {
            "numOfRows": 10,
            "pageNo": 1,
            "totalCount": 1094,
            "items": [
                {
                    "airline": "몽골항공",
                    "flightId": "OM308",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2358",
                    "airport": "신 울란바토르",
                    "gatenumber": "10",
                    "chkinrange": "K25-K34",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "UBN",
                    "yoil": null,
                    "himidity": null,
                    "wind": null,
                    "temp": null,
                    "senstemp": null,
                    "wimage": null,
                    "terminalid": "P01"
                },
                {
                    "airline": "대한항공",
                    "flightId": "KE5649",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2358",
                    "airport": "신 울란바토르",
                    "gatenumber": "10",
                    "chkinrange": "K25-K34",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "UBN",
                    "yoil": null,
                    "himidity": null,
                    "wind": null,
                    "temp": null,
                    "senstemp": null,
                    "wimage": null,
                    "terminalid": "P01"
                },
                {
                    "airline": "산동항공",
                    "flightId": "SC8004Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2352",
                    "airport": "지난",
                    "gatenumber": "14",
                    "chkinrange": "N03-N15",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "TNA",
                    "yoil": "목",
                    "himidity": "74",
                    "wind": "2.6",
                    "temp": "28.0",
                    "senstemp": "31.3",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon01",
                    "terminalid": "P01"
                },
                {
                    "airline": "중국국제항공",
                    "flightId": "CA8876Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2352",
                    "airport": "지난",
                    "gatenumber": "14",
                    "chkinrange": "N03-N15",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "TNA",
                    "yoil": "목",
                    "himidity": "74",
                    "wind": "2.6",
                    "temp": "28.0",
                    "senstemp": "31.3",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon01",
                    "terminalid": "P01"
                },
                {
                    "airline": "아시아나항공",
                    "flightId": "OZ6705Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2352",
                    "airport": "지난",
                    "gatenumber": "14",
                    "chkinrange": "N03-N15",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "TNA",
                    "yoil": "목",
                    "himidity": "74",
                    "wind": "2.6",
                    "temp": "28.0",
                    "senstemp": "31.3",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon01",
                    "terminalid": "P01"
                },
                {
                    "airline": "대한항공",
                    "flightId": "KE647Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2335",
                    "airport": "싱가포르",
                    "gatenumber": "233",
                    "chkinrange": "A B C D F",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "SIN",
                    "yoil": "목",
                    "himidity": "70",
                    "wind": "2.6",
                    "temp": "29.0",
                    "senstemp": "32.7",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon02",
                    "terminalid": "P03"
                },
                {
                    "airline": "델타항공",
                    "flightId": "DL7823Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2335",
                    "airport": "싱가포르",
                    "gatenumber": "233",
                    "chkinrange": "A B C D F",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "SIN",
                    "yoil": "목",
                    "himidity": "70",
                    "wind": "2.6",
                    "temp": "29.0",
                    "senstemp": "32.7",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon02",
                    "terminalid": "P03"
                },
                {
                    "airline": "웨스트젯",
                    "flightId": "WS6065Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2335",
                    "airport": "싱가포르",
                    "gatenumber": "233",
                    "chkinrange": "A B C D F",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "SIN",
                    "yoil": "목",
                    "himidity": "70",
                    "wind": "2.6",
                    "temp": "29.0",
                    "senstemp": "32.7",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon02",
                    "terminalid": "P03"
                },
                {
                    "airline": "스리랑카항공",
                    "flightId": "UL3815Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2335",
                    "airport": "싱가포르",
                    "gatenumber": "233",
                    "chkinrange": "A B C D F",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "SIN",
                    "yoil": "목",
                    "himidity": "70",
                    "wind": "2.6",
                    "temp": "29.0",
                    "senstemp": "32.7",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon02",
                    "terminalid": "P03"
                },
                {
                    "airline": "에미레이트항공",
                    "flightId": "EK323Y",
                    "scheduleDateTime": "0005",
                    "estimatedDateTime": "2346",
                    "airport": "두바이",
                    "gatenumber": "43",
                    "chkinrange": "K01-K12",
                    "exitnumber": null,
                    "remark": "출발",
                    "airportCode": "DXB",
                    "yoil": "목",
                    "himidity": "29",
                    "wind": "4.1",
                    "temp": "37.0",
                    "senstemp": "37.4",
                    "wimage": "https://odp.airport.kr/apiPortal/weather_icon/icon01",
                    "terminalid": "P01"
                }
            ]
        }
    }
}

In [16]:
print(data['response']['body']['items'][0])

{'airline': '몽골항공', 'flightId': 'OM308', 'scheduleDateTime': '0005', 'estimatedDateTime': '2358', 'airport': '신 울란바토르', 'gatenumber': '10', 'chkinrange': 'K25-K34', 'exitnumber': None, 'remark': '출발', 'airportCode': 'UBN', 'yoil': None, 'himidity': None, 'wind': None, 'temp': None, 'senstemp': None, 'wimage': None, 'terminalid': 'P01'}

- 구분: 실시간
- 인천국제공항공사_주차장별 요금 부과 기준 정보

In [67]:
url = 'http://apis.data.go.kr/B551177/ParkingChargeInfo/getParkingChargeInformation'
params ={'serviceKey' : 'ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==', 'numOfRows' : '100', 'pageNo' : '1', 'type' : 'json' }

response = requests.get(url, params=params)

data = response.json() #json디코딩
formatted = json.dumps(data, indent=4, ensure_ascii=False)
print(formatted)

{
    "response": {
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL SERVICE."
        },
        "body": {
            "numOfRows": 100,
            "pageNo": 1,
            "totalCount": 33,
            "items": [
                {
                    "charid": "FB00000001",
                    "chardesc": "최초 00:30 에 한해 1200원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000001",
                    "chardesc": "00:15 초과 시 600원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000002",
                    "chardesc": "01:00 초과 시 1000원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000003",
                    "chardesc": "00:30 초과 시 1200원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000004",
                    "chardesc": "최초 01:00 에 한해 500원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000004",
                    "chardesc": "00:15 초과 시 500원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000005",
                    "chardesc": "최초 01:00 에 한해 600원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000005",
                    "chardesc": "00:15 초과 시 600원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000006",
                    "chardesc": "01:00 초과 시 0원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000007",
                    "chardesc": "최초 01:00 에 한해 300원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000007",
                    "chardesc": "00:15 초과 시 300원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000008",
                    "chardesc": "최초 00:30 에 한해 1200원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000008",
                    "chardesc": "00:15 초과 시 600원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000009",
                    "chardesc": "01:00 초과 시 1000원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000010",
                    "chardesc": "01:00 초과 시 1000원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000011",
                    "chardesc": "01:00 초과 시 0원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000012",
                    "chardesc": "최초 00:30 에 한해 1200원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000012",
                    "chardesc": "00:15 초과 시 600원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000013",
                    "chardesc": "최초 01:00 에 한해 100원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000013",
                    "chardesc": "01:00 초과 시 100원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000014",
                    "chardesc": "최초 01:00 에 한해 100원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "FB00000014",
                    "chardesc": "01:00 초과 시 100원 부과",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000001",
                    "chardesc": "일일 최대 24000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000002",
                    "chardesc": "일일 최대 9000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000003",
                    "chardesc": "일일 최대 12000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000004",
                    "chardesc": "일일 최대 10000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000005",
                    "chardesc": "일일 최대 12000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000008",
                    "chardesc": "일일 최대 12000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000009",
                    "chardesc": "일일 최대 24000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000010",
                    "chardesc": "일일 최대 9000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000011",
                    "chardesc": "일일 최대 24000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000012",
                    "chardesc": "일일 최대 1000원 적용",
                    "datetime": "202507070630"
                },
                {
                    "charid": "NF00000013",
                    "chardesc": "일일 최대 1000원 적용",
                    "datetime": "202507070630"
                }
            ]
        }
    }
}

- 구분: 실시간
- 인천국제공항공사_주차장 현황

In [3]:
url = 'http://apis.data.go.kr/B551177/StatusOfParking/getTrackingParking'
params ={'serviceKey' : 'ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==', 'numOfRows' : '100', 'pageNo' : '1', 'type' : 'json' }

response = requests.get(url, params=params)

data = response.json()
formatted = json.dumps(data, indent=4, ensure_ascii=False)
print(formatted)

{
    "response": {
        "body": {
            "numOfRows": 100,
            "pageNo": 1,
            "totalCount": 17,
            "items": [
                {
                    "floor": "T1 단기주차장지상층",
                    "parking": "860",
                    "parkingarea": "1052",
                    "datetm": "20250711121809.403"
                },
                {
                    "floor": "T1 단기주차장지하1층",
                    "parking": "666",
                    "parkingarea": "1005",
                    "datetm": "20250711121809.403"
                },
                {
                    "floor": "T1 단기주차장지하2층",
                    "parking": "1344",
                    "parkingarea": "1334",
                    "datetm": "20250711121809.403"
                },
                {
                    "floor": "T2 단기주차장지상1층",
                    "parking": "638",
                    "parkingarea": "988",
                    "datetm": "20250711121809.401"
                },
                {
                    "floor": "T2 단기주차장지상2층",
                    "parking": "713",
                    "parkingarea": "947",
                    "datetm": "20250711121809.401"
                },
                {
                    "floor": "T2 단기주차장지상3층",
                    "parking": "562",
                    "parkingarea": "896",
                    "datetm": "20250711121809.401"
                },
                {
                    "floor": "T2 단기주차장지상4층",
                    "parking": "787",
                    "parkingarea": "976",
                    "datetm": "20250711121809.401"
                },
                {
                    "floor": "T2 단기주차장지하M층",
                    "parking": "481",
                    "parkingarea": "751",
                    "datetm": "20250711121809.401"
                },
                {
                    "floor": "T1 장기 P1 주차장",
                    "parking": "3369",
                    "parkingarea": "2769",
                    "datetm": "20250711121809.404"
                },
                {
                    "floor": "T1 장기 P1 주차타워",
                    "parking": "1377",
                    "parkingarea": "1379",
                    "datetm": "20250711121809.406"
                },
                {
                    "floor": "T1 장기 P2 주차타워",
                    "parking": "1379",
                    "parkingarea": "1379",
                    "datetm": "20250711121809.407"
                },
                {
                    "floor": "T1 장기 P2 주차장",
                    "parking": "3071",
                    "parkingarea": "2581",
                    "datetm": "20250711121809.405"
                },
                {
                    "floor": "T1 장기 P3 주차장",
                    "parking": "1355",
                    "parkingarea": "1605",
                    "datetm": "20250711121809.408"
                },
                {
                    "floor": "T1 장기 P4 주차장",
                    "parking": "824",
                    "parkingarea": "1727",
                    "datetm": "20250711121809.411"
                },
                {
                    "floor": "T1 P5 예약주차장",
                    "parking": "1117",
                    "parkingarea": "1256",
                    "datetm": "20250711121809.409"
                },
                {
                    "floor": "T2 장기 주차장",
                    "parking": "4409",
                    "parkingarea": "9296",
                    "datetm": "20250711121809.402"
                },
                {
                    "floor": "T2 예약 주차장",
                    "parking": "774",
                    "parkingarea": "924",
                    "datetm": "20250711121809.410"
                }
            ]
        },
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL SERVICE."
        }
    }
}

In [4]:
data['response']['body']['items']

[{'floor': 'T1 단기주차장지상층',
  'parking': '860',
  'parkingarea': '1052',
  'datetm': '20250711121809.403'},
 {'floor': 'T1 단기주차장지하1층',
  'parking': '666',
  'parkingarea': '1005',
  'datetm': '20250711121809.403'},
 {'floor': 'T1 단기주차장지하2층',
  'parking': '1344',
  'parkingarea': '1334',
  'datetm': '20250711121809.403'},
 {'floor': 'T2 단기주차장지상1층',
  'parking': '638',
  'parkingarea': '988',
  'datetm': '20250711121809.401'},
 {'floor': 'T2 단기주차장지상2층',
  'parking': '713',
  'parkingarea': '947',
  'datetm': '20250711121809.401'},
 {'floor': 'T2 단기주차장지상3층',
  'parking': '562',
  'parkingarea': '896',
  'datetm': '20250711121809.401'},
 {'floor': 'T2 단기주차장지상4층',
  'parking': '787',
  'parkingarea': '976',
  'datetm': '20250711121809.401'},
 {'floor': 'T2 단기주차장지하M층',
  'parking': '481',
  'parkingarea': '751',
  'datetm': '20250711121809.401'},
 {'floor': 'T1 장기 P1 주차장',
  'parking': '3369',
  'parkingarea': '2769',
  'datetm': '20250711121809.404'},
 {'floor': 'T1 장기 P1 주차타워',
  'parking': '1377',
  'parkingarea': '1379',
  'datetm': '20250711121809.406'},
 {'floor': 'T1 장기 P2 주차타워',
  'parking': '1379',
  'parkingarea': '1379',
  'datetm': '20250711121809.407'},
 {'floor': 'T1 장기 P2 주차장',
  'parking': '3071',
  'parkingarea': '2581',
  'datetm': '20250711121809.405'},
 {'floor': 'T1 장기 P3 주차장',
  'parking': '1355',
  'parkingarea': '1605',
  'datetm': '20250711121809.408'},
 {'floor': 'T1 장기 P4 주차장',
  'parking': '824',
  'parkingarea': '1727',
  'datetm': '20250711121809.411'},
 {'floor': 'T1 P5 예약주차장',
  'parking': '1117',
  'parkingarea': '1256',
  'datetm': '20250711121809.409'},
 {'floor': 'T2 장기 주차장',
  'parking': '4409',
  'parkingarea': '9296',
  'datetm': '20250711121809.402'},
 {'floor': 'T2 예약 주차장',
  'parking': '774',
  'parkingarea': '924',
  'datetm': '20250711121809.410'}]

- 구분: 실시간
- 인천국제공항공사_실내대기질정보

In [42]:
print(response.status_code)
print(response.headers.get('Content-Type'))
print(response.text[:])

500
text/xml;charset=utf-8
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
    <soapenv:Body>
        <soapenv:Fault>
            <faultcode>soapenv:Server</faultcode>
            <faultstring>Policy Falsified</faultstring>
            <faultactor>http://apis.data.go.kr/B551177/IndoorAirQualityInformation/getIndoorAirQos?serviceKey=ZD3OIVINNmYvDgo1FjLk8%2F82%2FbeKJKJhGNRb61laL%2BjH9rK6Ei0419SnoUBsvXd2%2Fe%2BUO%2FbLHa6Pq21D1CZpLA%3D%3D&amp;type=json&amp;numOfRows=100&amp;pageNo=1</faultactor>
            <detail>
                <l7:policyResult
                    status="Service Not Found.  The request may have been sent to an invalid URL, or intended for an unsupported operation." xmlns:l7="http://www.layer7tech.com/ws/policy/fault"/>
            </detail>
        </soapenv:Fault>
    </soapenv:Body>
</soapenv:Envelope>

In [57]:
url = "http://apis.data.go.kr/B551177/IndoorAirQualityInformation/getIndoorAirQs"
params = {
    'serviceKey': 'ZD3OIVINNmYvDgo1FjLk8/82/beKJKJhGNRb61laL+jH9rK6Ei0419SnoUBsvXd2/e+UO/bLHa6Pq21D1CZpLA==',
    'type': 'json',
    'pageNo': '1',
    'numOfRows': '100'
}


response = requests.get(url, params=params)
data = response.json()
formatted = json.dumps(data, indent=4)
print(formatted)

{
    "response": {
        "header": {
            "resultCode": "00",
            "resultMsg": "NORMAL SERVICE."
        },
        "body": {
            "numOfRows": 100,
            "pageNo": 1,
            "totalCount": 3,
            "items": [
                {
                    "terminalid": "T1",
                    "rtime": "2025071113",
                    "co2": "657",
                    "pm10": "14.7",
                    "pm2_5": "5.7",
                    "co": "0.6",
                    "no2": "0.02"
                },
                {
                    "terminalid": "T2",
                    "rtime": "2025071113",
                    "co2": "548",
                    "pm10": "21.8",
                    "pm2_5": "11.5",
                    "co": "0.4",
                    "no2": "0.038"
                },
                {
                    "terminalid": "\ud0d1\uc2b9\ub3d9",
                    "rtime": "2025071113",
                    "co2": "800",
                    "pm10": "16.8",
                    "pm2_5": "2.2",
                    "co": "0.4",
                    "no2": "0.017"
                }
            ]
        }
    }
}